# Generated by Django 4.1.2 on 2023-09-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('anuncio', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('contacto', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='datos',
            fields=[
                ('usuario', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('otros_datos', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='estilo',
            fields=[
                ('usuario', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('instrumento1', models.CharField(max_length=30)),
                ('instrumento2', models.CharField(max_length=30)),
                ('instrumento3', models.CharField(max_length=30)),
                ('estilo1', models.CharField(max_length=30)),
                ('estilo2', models.CharField(max_length=30)),
                ('estilo3', models.CharField(max_length=30)),
                ('artista1', models.CharField(max_length=30)),
                ('artista2', models.CharField(max_length=30)),
                ('artista3', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('para', models.CharField(max_length=30)),
                ('mensaje', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='multimedia',
            fields=[
                ('usuario', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('imagen1', models.ImageField(null=True, upload_to='media/')),
                ('imagen2', models.ImageField(null=True, upload_to='media/')),
                ('imagen3', models.ImageField(null=True, upload_to='media/')),
                ('imagen4', models.ImageField(null=True, upload_to='media/')),
                ('imagen5', models.ImageField(null=True, upload_to='media/')),
                ('video1', models.FileField(null=True, upload_to='media/')),
                ('video2', models.FileField(null=True, upload_to='media/')),
                ('video3', models.FileField(null=True, upload_to='media/')),
                ('video4', models.FileField(null=True, upload_to='media/')),
                ('video5', models.FileField(null=True, upload_to='media/')),
                ('audio1', models.FileField(null=True, upload_to='media/')),
                ('audio2', models.FileField(null=True, upload_to='media/')),
                ('audio3', models.FileField(null=True, upload_to='media/')),
                ('audio4', models.FileField(null=True, upload_to='media/')),
                ('audio5', models.FileField(null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='musico',
            fields=[
                ('usuario', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('region', models.CharField(max_length=30)),
                ('comuna', models.CharField(max_length=30)),
                ('disponibilidad', models.CharField(max_length=30)),
                ('carrera', models.CharField(max_length=30)),
                ('banda', models.CharField(max_length=30)),
                ('instrumento1', models.CharField(max_length=30)),
                ('instrumento2', models.CharField(max_length=30)),
                ('instrumento3', models.CharField(max_length=30)),
                ('estilo1', models.CharField(max_length=30)),
                ('estilo2', models.CharField(max_length=30)),
                ('estilo3', models.CharField(max_length=30)),
                ('artista1', models.CharField(max_length=30)),
                ('artista2', models.CharField(max_length=30)),
                ('artista3', models.CharField(max_length=30)),
                ('imagen', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
    ]
