# Generated by Django 4.1.2 on 2023-09-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mensajeadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=50)),
                ('mensaje', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
